### ISSUE TITLE
Balloon Game

### ISSUE THREAD

**Issue by Wyrd00** [facn2/neuro-games#11]
- [x] Create HTML;
- [x] Use canvas to draw the balloon;
- [x] Make balloon react to user input;
- [x] add game finish message

**Comment by Karyum** [comment]
@KatiaAsh @Wyrd00 @tyeung2017 are you going to add the option to replay thew game later on or something else ??

**Comment by KatiaAsh** [comment]
@Karyum No, when you finish you'll see the result and a button to go to next game
