### ISSUE TITLE
User Journey - As a user I want to play games and get result on my cognitive traits

### ISSUE THREAD

**Issue by Wyrd00** [facn2/neuro-games#21]
- [x] View landing page #27 
- [x] Read general guideline for site #4 
- [x] Read instructions for first game #5
- [x] Play the first game #10
- [x] See immediate feedback displaying attributes #6 
- [x] See compiled traits after completion of all games #7
