### ISSUE TITLE
Stretch Goals

### ISSUE THREAD

**Issue by Wyrd00** [facn2/neuro-games#31]
- [ ] Create graphs for traits
- [x] More games [UPDATE: working on hanoi game]
- [ ] Add user profile
- [x] Add degree/education/school options [UPDATE: degree]
   - [ ] Step-by-step achievement
